//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublishService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    public class ArrayOfInt : System.Collections.Generic.List<int>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PublishService.PublishServiceSoap")]
    public interface PublishServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportAndPublishInv", ReplyAction="*")]
        System.Threading.Tasks.Task<PublishService.ImportAndPublishInvResponse> ImportAndPublishInvAsync(PublishService.ImportAndPublishInvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInvPattern", ReplyAction="*")]
        System.Threading.Tasks.Task<PublishService.ImportInvPatternResponse> ImportInvPatternAsync(PublishService.ImportInvPatternRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInv", ReplyAction="*")]
        System.Threading.Tasks.Task<PublishService.ImportInvResponse> ImportInvAsync(PublishService.ImportInvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishInv", ReplyAction="*")]
        System.Threading.Tasks.Task<PublishService.publishInvResponse> publishInvAsync(PublishService.publishInvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCus", ReplyAction="*")]
        System.Threading.Tasks.Task<PublishService.UpdateCusResponse> UpdateCusAsync(PublishService.UpdateCusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCusCert", ReplyAction="*")]
        System.Threading.Tasks.Task<PublishService.setCusCertResponse> setCusCertAsync(PublishService.setCusCertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInvByPatternSerial", ReplyAction="*")]
        System.Threading.Tasks.Task<PublishService.ImportInvByPatternSerialResponse> ImportInvByPatternSerialAsync(PublishService.ImportInvByPatternSerialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishInvFkey", ReplyAction="*")]
        System.Threading.Tasks.Task<PublishService.publishInvFkeyResponse> publishInvFkeyAsync(PublishService.publishInvFkeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteInvFkey", ReplyAction="*")]
        System.Threading.Tasks.Task<PublishService.deleteInvFkeyResponse> deleteInvFkeyAsync(PublishService.deleteInvFkeyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportAndPublishInvRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportAndPublishInv", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.ImportAndPublishInvRequestBody Body;
        
        public ImportAndPublishInvRequest()
        {
        }
        
        public ImportAndPublishInvRequest(PublishService.ImportAndPublishInvRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportAndPublishInvRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int convert;
        
        public ImportAndPublishInvRequestBody()
        {
        }
        
        public ImportAndPublishInvRequestBody(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial, int convert)
        {
            this.Account = Account;
            this.ACpass = ACpass;
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.pattern = pattern;
            this.serial = serial;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportAndPublishInvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportAndPublishInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.ImportAndPublishInvResponseBody Body;
        
        public ImportAndPublishInvResponse()
        {
        }
        
        public ImportAndPublishInvResponse(PublishService.ImportAndPublishInvResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportAndPublishInvResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportAndPublishInvResult;
        
        public ImportAndPublishInvResponseBody()
        {
        }
        
        public ImportAndPublishInvResponseBody(string ImportAndPublishInvResult)
        {
            this.ImportAndPublishInvResult = ImportAndPublishInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvPatternRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvPattern", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.ImportInvPatternRequestBody Body;
        
        public ImportInvPatternRequest()
        {
        }
        
        public ImportInvPatternRequest(PublishService.ImportInvPatternRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvPatternRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int convert;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string serial;
        
        public ImportInvPatternRequestBody()
        {
        }
        
        public ImportInvPatternRequestBody(string xmlInvData, string username, string password, int convert, string pattern, string serial)
        {
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.convert = convert;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvPatternResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvPatternResponse", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.ImportInvPatternResponseBody Body;
        
        public ImportInvPatternResponse()
        {
        }
        
        public ImportInvPatternResponse(PublishService.ImportInvPatternResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvPatternResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportInvPatternResult;
        
        public ImportInvPatternResponseBody()
        {
        }
        
        public ImportInvPatternResponseBody(string ImportInvPatternResult)
        {
            this.ImportInvPatternResult = ImportInvPatternResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInv", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.ImportInvRequestBody Body;
        
        public ImportInvRequest()
        {
        }
        
        public ImportInvRequest(PublishService.ImportInvRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int convert;
        
        public ImportInvRequestBody()
        {
        }
        
        public ImportInvRequestBody(string xmlInvData, string username, string password, int convert)
        {
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.ImportInvResponseBody Body;
        
        public ImportInvResponse()
        {
        }
        
        public ImportInvResponse(PublishService.ImportInvResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportInvResult;
        
        public ImportInvResponseBody()
        {
        }
        
        public ImportInvResponseBody(string ImportInvResult)
        {
            this.ImportInvResult = ImportInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInv", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.publishInvRequestBody Body;
        
        public publishInvRequest()
        {
        }
        
        public publishInvRequest(PublishService.publishInvRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PublishService.ArrayOfInt invIDs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string serial;
        
        public publishInvRequestBody()
        {
        }
        
        public publishInvRequestBody(PublishService.ArrayOfInt invIDs, string username, string password, string pattern, string serial)
        {
            this.invIDs = invIDs;
            this.username = username;
            this.password = password;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.publishInvResponseBody Body;
        
        public publishInvResponse()
        {
        }
        
        public publishInvResponse(PublishService.publishInvResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publishInvResult;
        
        public publishInvResponseBody()
        {
        }
        
        public publishInvResponseBody(string publishInvResult)
        {
            this.publishInvResult = publishInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCus", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.UpdateCusRequestBody Body;
        
        public UpdateCusRequest()
        {
        }
        
        public UpdateCusRequest(PublishService.UpdateCusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XMLCusData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> convert;
        
        public UpdateCusRequestBody()
        {
        }
        
        public UpdateCusRequestBody(string XMLCusData, string username, string pass, System.Nullable<int> convert)
        {
            this.XMLCusData = XMLCusData;
            this.username = username;
            this.pass = pass;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCusResponse", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.UpdateCusResponseBody Body;
        
        public UpdateCusResponse()
        {
        }
        
        public UpdateCusResponse(PublishService.UpdateCusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateCusResult;
        
        public UpdateCusResponseBody()
        {
        }
        
        public UpdateCusResponseBody(int UpdateCusResult)
        {
            this.UpdateCusResult = UpdateCusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCusCertRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCusCert", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.setCusCertRequestBody Body;
        
        public setCusCertRequest()
        {
        }
        
        public setCusCertRequest(PublishService.setCusCertRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCusCertRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string certSerial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string certString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cusCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        public setCusCertRequestBody()
        {
        }
        
        public setCusCertRequestBody(string certSerial, string certString, string cusCode, string username, string pass)
        {
            this.certSerial = certSerial;
            this.certString = certString;
            this.cusCode = cusCode;
            this.username = username;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCusCertResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCusCertResponse", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.setCusCertResponseBody Body;
        
        public setCusCertResponse()
        {
        }
        
        public setCusCertResponse(PublishService.setCusCertResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCusCertResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int setCusCertResult;
        
        public setCusCertResponseBody()
        {
        }
        
        public setCusCertResponseBody(int setCusCertResult)
        {
            this.setCusCertResult = setCusCertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvByPatternSerialRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvByPatternSerial", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.ImportInvByPatternSerialRequestBody Body;
        
        public ImportInvByPatternSerialRequest()
        {
        }
        
        public ImportInvByPatternSerialRequest(PublishService.ImportInvByPatternSerialRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvByPatternSerialRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int convert;
        
        public ImportInvByPatternSerialRequestBody()
        {
        }
        
        public ImportInvByPatternSerialRequestBody(string xmlInvData, string username, string pass, string pattern, string serial, int convert)
        {
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.pass = pass;
            this.pattern = pattern;
            this.serial = serial;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvByPatternSerialResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvByPatternSerialResponse", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.ImportInvByPatternSerialResponseBody Body;
        
        public ImportInvByPatternSerialResponse()
        {
        }
        
        public ImportInvByPatternSerialResponse(PublishService.ImportInvByPatternSerialResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvByPatternSerialResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportInvByPatternSerialResult;
        
        public ImportInvByPatternSerialResponseBody()
        {
        }
        
        public ImportInvByPatternSerialResponseBody(string ImportInvByPatternSerialResult)
        {
            this.ImportInvByPatternSerialResult = ImportInvByPatternSerialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvFkeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvFkey", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.publishInvFkeyRequestBody Body;
        
        public publishInvFkeyRequest()
        {
        }
        
        public publishInvFkeyRequest(PublishService.publishInvFkeyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvFkeyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lsFkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string serial;
        
        public publishInvFkeyRequestBody()
        {
        }
        
        public publishInvFkeyRequestBody(string Account, string ACpass, string lsFkey, string userName, string pass, string pattern, string serial)
        {
            this.Account = Account;
            this.ACpass = ACpass;
            this.lsFkey = lsFkey;
            this.userName = userName;
            this.pass = pass;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvFkeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvFkeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.publishInvFkeyResponseBody Body;
        
        public publishInvFkeyResponse()
        {
        }
        
        public publishInvFkeyResponse(PublishService.publishInvFkeyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvFkeyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publishInvFkeyResult;
        
        public publishInvFkeyResponseBody()
        {
        }
        
        public publishInvFkeyResponseBody(string publishInvFkeyResult)
        {
            this.publishInvFkeyResult = publishInvFkeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteInvFkeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteInvFkey", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.deleteInvFkeyRequestBody Body;
        
        public deleteInvFkeyRequest()
        {
        }
        
        public deleteInvFkeyRequest(PublishService.deleteInvFkeyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteInvFkeyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lsFkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        public deleteInvFkeyRequestBody()
        {
        }
        
        public deleteInvFkeyRequestBody(string lsFkey, string Account, string ACpass, string userName, string pass, string pattern)
        {
            this.lsFkey = lsFkey;
            this.Account = Account;
            this.ACpass = ACpass;
            this.userName = userName;
            this.pass = pass;
            this.pattern = pattern;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteInvFkeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteInvFkeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public PublishService.deleteInvFkeyResponseBody Body;
        
        public deleteInvFkeyResponse()
        {
        }
        
        public deleteInvFkeyResponse(PublishService.deleteInvFkeyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteInvFkeyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteInvFkeyResult;
        
        public deleteInvFkeyResponseBody()
        {
        }
        
        public deleteInvFkeyResponseBody(string deleteInvFkeyResult)
        {
            this.deleteInvFkeyResult = deleteInvFkeyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface PublishServiceSoapChannel : PublishService.PublishServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PublishServiceSoapClient : System.ServiceModel.ClientBase<PublishService.PublishServiceSoap>, PublishService.PublishServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PublishServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PublishServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), PublishServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PublishServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PublishServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PublishServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PublishServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PublishServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PublishService.ImportAndPublishInvResponse> PublishService.PublishServiceSoap.ImportAndPublishInvAsync(PublishService.ImportAndPublishInvRequest request)
        {
            return base.Channel.ImportAndPublishInvAsync(request);
        }
        
        public System.Threading.Tasks.Task<PublishService.ImportAndPublishInvResponse> ImportAndPublishInvAsync(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial, int convert)
        {
            PublishService.ImportAndPublishInvRequest inValue = new PublishService.ImportAndPublishInvRequest();
            inValue.Body = new PublishService.ImportAndPublishInvRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            inValue.Body.convert = convert;
            return ((PublishService.PublishServiceSoap)(this)).ImportAndPublishInvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PublishService.ImportInvPatternResponse> PublishService.PublishServiceSoap.ImportInvPatternAsync(PublishService.ImportInvPatternRequest request)
        {
            return base.Channel.ImportInvPatternAsync(request);
        }
        
        public System.Threading.Tasks.Task<PublishService.ImportInvPatternResponse> ImportInvPatternAsync(string xmlInvData, string username, string password, int convert, string pattern, string serial)
        {
            PublishService.ImportInvPatternRequest inValue = new PublishService.ImportInvPatternRequest();
            inValue.Body = new PublishService.ImportInvPatternRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.convert = convert;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            return ((PublishService.PublishServiceSoap)(this)).ImportInvPatternAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PublishService.ImportInvResponse> PublishService.PublishServiceSoap.ImportInvAsync(PublishService.ImportInvRequest request)
        {
            return base.Channel.ImportInvAsync(request);
        }
        
        public System.Threading.Tasks.Task<PublishService.ImportInvResponse> ImportInvAsync(string xmlInvData, string username, string password, int convert)
        {
            PublishService.ImportInvRequest inValue = new PublishService.ImportInvRequest();
            inValue.Body = new PublishService.ImportInvRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.convert = convert;
            return ((PublishService.PublishServiceSoap)(this)).ImportInvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PublishService.publishInvResponse> PublishService.PublishServiceSoap.publishInvAsync(PublishService.publishInvRequest request)
        {
            return base.Channel.publishInvAsync(request);
        }
        
        public System.Threading.Tasks.Task<PublishService.publishInvResponse> publishInvAsync(PublishService.ArrayOfInt invIDs, string username, string password, string pattern, string serial)
        {
            PublishService.publishInvRequest inValue = new PublishService.publishInvRequest();
            inValue.Body = new PublishService.publishInvRequestBody();
            inValue.Body.invIDs = invIDs;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            return ((PublishService.PublishServiceSoap)(this)).publishInvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PublishService.UpdateCusResponse> PublishService.PublishServiceSoap.UpdateCusAsync(PublishService.UpdateCusRequest request)
        {
            return base.Channel.UpdateCusAsync(request);
        }
        
        public System.Threading.Tasks.Task<PublishService.UpdateCusResponse> UpdateCusAsync(string XMLCusData, string username, string pass, System.Nullable<int> convert)
        {
            PublishService.UpdateCusRequest inValue = new PublishService.UpdateCusRequest();
            inValue.Body = new PublishService.UpdateCusRequestBody();
            inValue.Body.XMLCusData = XMLCusData;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.convert = convert;
            return ((PublishService.PublishServiceSoap)(this)).UpdateCusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PublishService.setCusCertResponse> PublishService.PublishServiceSoap.setCusCertAsync(PublishService.setCusCertRequest request)
        {
            return base.Channel.setCusCertAsync(request);
        }
        
        public System.Threading.Tasks.Task<PublishService.setCusCertResponse> setCusCertAsync(string certSerial, string certString, string cusCode, string username, string pass)
        {
            PublishService.setCusCertRequest inValue = new PublishService.setCusCertRequest();
            inValue.Body = new PublishService.setCusCertRequestBody();
            inValue.Body.certSerial = certSerial;
            inValue.Body.certString = certString;
            inValue.Body.cusCode = cusCode;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            return ((PublishService.PublishServiceSoap)(this)).setCusCertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PublishService.ImportInvByPatternSerialResponse> PublishService.PublishServiceSoap.ImportInvByPatternSerialAsync(PublishService.ImportInvByPatternSerialRequest request)
        {
            return base.Channel.ImportInvByPatternSerialAsync(request);
        }
        
        public System.Threading.Tasks.Task<PublishService.ImportInvByPatternSerialResponse> ImportInvByPatternSerialAsync(string xmlInvData, string username, string pass, string pattern, string serial, int convert)
        {
            PublishService.ImportInvByPatternSerialRequest inValue = new PublishService.ImportInvByPatternSerialRequest();
            inValue.Body = new PublishService.ImportInvByPatternSerialRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            inValue.Body.convert = convert;
            return ((PublishService.PublishServiceSoap)(this)).ImportInvByPatternSerialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PublishService.publishInvFkeyResponse> PublishService.PublishServiceSoap.publishInvFkeyAsync(PublishService.publishInvFkeyRequest request)
        {
            return base.Channel.publishInvFkeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<PublishService.publishInvFkeyResponse> publishInvFkeyAsync(string Account, string ACpass, string lsFkey, string userName, string pass, string pattern, string serial)
        {
            PublishService.publishInvFkeyRequest inValue = new PublishService.publishInvFkeyRequest();
            inValue.Body = new PublishService.publishInvFkeyRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.lsFkey = lsFkey;
            inValue.Body.userName = userName;
            inValue.Body.pass = pass;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            return ((PublishService.PublishServiceSoap)(this)).publishInvFkeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PublishService.deleteInvFkeyResponse> PublishService.PublishServiceSoap.deleteInvFkeyAsync(PublishService.deleteInvFkeyRequest request)
        {
            return base.Channel.deleteInvFkeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<PublishService.deleteInvFkeyResponse> deleteInvFkeyAsync(string lsFkey, string Account, string ACpass, string userName, string pass, string pattern)
        {
            PublishService.deleteInvFkeyRequest inValue = new PublishService.deleteInvFkeyRequest();
            inValue.Body = new PublishService.deleteInvFkeyRequestBody();
            inValue.Body.lsFkey = lsFkey;
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.userName = userName;
            inValue.Body.pass = pass;
            inValue.Body.pattern = pattern;
            return ((PublishService.PublishServiceSoap)(this)).deleteInvFkeyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PublishServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PublishServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PublishServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://saigontouristbinhduongadmindemo.vnpt-invoice.com.vn/PublishService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PublishServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://saigontouristbinhduongadmindemo.vnpt-invoice.com.vn/PublishService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PublishServiceSoap,
            
            PublishServiceSoap12,
        }
    }
}
